export const themeJson = {

  "backgroundOpacity": 1,
  "isPanelless": true,
  "cssVariables": {
    "--sjs-general-backcolor": "#ffffff",
    "--sjs-general-backcolor-dark": "#f8f8f8",
    "--sjs-general-backcolor-dim": "#ffffff",
    "--sjs-general-backcolor-dim-light": "#f9f9f9",
    "--sjs-general-backcolor-dim-dark": "#f3f3f3",
    "--sjs-general-forecolor": "#262626",
    "--sjs-general-forecolor-light": "rgba(38, 38, 38, 0.7)",
    "--sjs-general-dim-forecolor": "#262626",
    "--sjs-general-dim-forecolor-light": "rgba(38, 38, 38, 0.7)",
    "--sjs-primary-backcolor": "#3b82f6",
    "--sjs-primary-backcolor-light": "rgba(59, 130, 246, 0.2)",
    "--sjs-primary-backcolor-dark": "#2563eb",
    "--sjs-primary-forecolor": "#ffffff",
    "--sjs-primary-forecolor-light": "rgba(255, 255, 255, 0.6)",
    "--sjs-base-unit": "8px",
    "--sjs-corner-radius": "6px",
    "--sjs-secondary-backcolor": "#f59e0b",
    "--sjs-secondary-backcolor-light": "rgba(245, 158, 11, 0.2)",
    "--sjs-secondary-backcolor-semi-light": "rgba(245, 158, 11, 0.4)",
    "--sjs-secondary-forecolor": "#ffffff",
    "--sjs-secondary-forecolor-light": "rgba(255, 255, 255, 0.6)",
    "--sjs-shadow-small": "0 1px 3px 0 rgba(0, 0, 0, 0.4)",
    "--sjs-shadow-small-reset": "none",
    "--sjs-shadow-medium": "0 4px 6px -1px rgba(0, 0, 0, 0.4)",
    "--sjs-shadow-large": "0 10px 15px -3px rgba(0, 0, 0, 0.4)",
    "--sjs-shadow-inner": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.4)",
    "--sjs-shadow-inner-reset": "none",
    "--sjs-border-light": "rgba(255, 255, 255, 0.2)",
    "--sjs-border-default": "rgba(255, 255, 255, 0.3)",
    "--sjs-border-inside": "rgba(255, 255, 255, 0.2)",
    "--sjs-special-red": "rgba(229, 10, 62, 1)",
    "--sjs-special-red-light": "rgba(229, 10, 62, 0.1)",
    "--sjs-special-red-forecolor": "rgba(255, 255, 255, 1)",
    "--sjs-special-green": "rgba(25, 179, 148, 1)",
    "--sjs-special-green-light": "rgba(25, 179, 148, 0.1)",
    "--sjs-special-green-forecolor": "rgba(255, 255, 255, 1)",
    "--sjs-special-blue": "rgba(67, 127, 217, 1)",
    "--sjs-special-blue-light": "rgba(67, 127, 217, 0.1)",
    "--sjs-special-blue-forecolor": "rgba(255, 255, 255, 1)",
    "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
    "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
    "--sjs-special-yellow-forecolor": "rgba(255, 255, 255, 1)",
    "--sjs-article-font-xx-large-textDecoration": "none",
    "--sjs-article-font-xx-large-fontWeight": "700",
    "--sjs-article-font-xx-large-fontStyle": "normal",
    "--sjs-article-font-xx-large-fontStretch": "normal",
    "--sjs-article-font-xx-large-letterSpacing": "0",
    "--sjs-article-font-xx-large-lineHeight": "64px",
    "--sjs-article-font-xx-large-paragraphIndent": "0px",
    "--sjs-article-font-xx-large-textCase": "none",
    "--sjs-article-font-x-large-textDecoration": "none",
    "--sjs-article-font-x-large-fontWeight": "700",
    "--sjs-article-font-x-large-fontStyle": "normal",
    "--sjs-article-font-x-large-fontStretch": "normal",
    "--sjs-article-font-x-large-letterSpacing": "0",
    "--sjs-article-font-x-large-lineHeight": "56px",
    "--sjs-article-font-x-large-paragraphIndent": "0px",
    "--sjs-article-font-x-large-textCase": "none",
    "--sjs-article-font-large-textDecoration": "none",
    "--sjs-article-font-large-fontWeight": "700",
    "--sjs-article-font-large-fontStyle": "normal",
    "--sjs-article-font-large-fontStretch": "normal",
    "--sjs-article-font-large-letterSpacing": "0",
    "--sjs-article-font-large-lineHeight": "40px",
    "--sjs-article-font-large-paragraphIndent": "0px",
    "--sjs-article-font-large-textCase": "none",
    "--sjs-article-font-medium-textDecoration": "none",
    "--sjs-article-font-medium-fontWeight": "700",
    "--sjs-article-font-medium-fontStyle": "normal",
    "--sjs-article-font-medium-fontStretch": "normal",
    "--sjs-article-font-medium-letterSpacing": "0",
    "--sjs-article-font-medium-lineHeight": "32px",
    "--sjs-article-font-medium-paragraphIndent": "0px",
    "--sjs-article-font-medium-textCase": "none",
    "--sjs-article-font-default-textDecoration": "none",
    "--sjs-article-font-default-fontWeight": "400",
    "--sjs-article-font-default-fontStyle": "normal",
    "--sjs-article-font-default-fontStretch": "normal",
    "--sjs-article-font-default-letterSpacing": "0",
    "--sjs-article-font-default-lineHeight": "28px",
    "--sjs-article-font-default-paragraphIndent": "0px",
    "--sjs-article-font-default-textCase": "none",
    "--sjs-article-font-xx-large-fontSize": "64px",
    "--sjs-article-font-x-large-fontSize": "48px",
    "--sjs-article-font-large-fontSize": "32px",
    "--sjs-article-font-medium-fontSize": "24px",
    "--sjs-article-font-default-fontSize": "16px",
    "--sjs-editor-background": "rgba(249, 249, 249, 1)",
    "--sjs-editorpanel-backcolor": "rgba(249, 249, 249, 0)",
    "--sjs-editorpanel-hovercolor": "rgba(243, 243, 243, 1)",
    "--sjs-editorpanel-cornerRadius": "0px",
    "--sjs-font-size": "16px",
    "--font-family": "Open Sans",
    "--sjs-font-editorfont-color": "rgba(0, 0, 0, 1)",
    "--sjs-font-editorfont-placeholdercolor": "rgba(0, 0, 0, 0.35)",
    "--sjs-font-surveytitle-size": "32px",
    "--sjs-font-pagetitle-color": "rgba(0, 0, 0, 0.9)",
    "--sjs-font-questiontitle-color": "rgba(0, 0, 0, 0.9)",
    "--sjs-font-questiondescription-color": "rgba(0, 0, 0, 0.35)",
    "--sjs-header-backcolor": "transparent",
    "--sjs-font-headerdescription-color": "rgba(0, 0, 0, 0.9)",
    "--sjs-font-headerdescription-weight": "700",
    "--sjs-font-headerdescription-size": "14px"
  },
  "themeName": "default",
  "colorPalette": "light",
  "header": {
    "height": 276,
    "inheritWidthFrom": "survey",
    "textAreaWidth": 600,
    "overlapEnabled": false,
    "backgroundImageOpacity": 1,
    "backgroundImageFit": "cover",
    "logoPositionX": "right",
    "logoPositionY": "middle",
    "titlePositionX": "left",
    "titlePositionY": "middle",
    "descriptionPositionX": "left",
    "descriptionPositionY": "middle"
  },
  "headerView": "advanced"
};

export const customCss = {
    footer: "sv_nav mt-10 flex justify-between",
    imagepicker: {
      item: "sv_q_imgsel w-full inline-block !mr-0 max-w-[10rem] text-center",
      image:
        "sv_image_image w-20 h-20 rounded-full bg-[#e0cfc7] checked:bg-[#e78370] mx-auto mt-3",
      root: "sv_imagesel flex flex-wrap justify-center",
      label: "sv_q_imgsel_label children:!border-0",
      itemInline: "sv_q_imagepicker_inline grow shrink basis-1/3 !leading-6",
      itemText: "sv_q_imgsel_text !break-normal !whitespace-normal",
      itemControl: "sv_q_imgsel_control_item hidden",
      mainRoot:
        "sv_q sv_qstn py-4 px-4 mt-3 border-b border-[#ddd] flex flex-col",
      itemChecked: "sd-imagepicker__item--checked checked",
      checkedItemDecorator: "hidden",
    },
    radiogroup: {
      label:
        "sv_q_radiogroup_label justify-left inline-block text-center border border-[#ccc] rounded-md w-full cursor-pointer p-2.5 checked:bg-primary checked:text-white",
      itemControl: "sv_q_radiogroup_control_item hidden",
      item: "sv_q_radiogroup w-full pr-2.5 max-w-[6.875rem] mb-4 mt-2 inline-block",
      root: "sv_qcbc text-center mt-2.5",
      itemChecked: "sd-item--checked sd-radio--checked checked",
    },
    checkbox: {
      root: "sv_qcbc flex flex-wrap gap-4 p-4",
      item: "sv_q_checkbox relative flex items-center p-3 border-2 rounded-lg hover:bg-gray-50 transition-colors cursor-pointer min-w-[200px] bg-white",
      itemChecked: "!border-blue-600",
      itemControl: "absolute inset-0 opacity-0 cursor-pointer",
      itemDecorator: "w-7 h-7 border-2 rounded-md mr-3 flex items-center justify-center transition-colors border-gray-400 bg-white",
      itemCheckedDecorator: "!border-blue-600 !bg-blue-600",
      itemText: "text-base font-medium flex-1 text-gray-900",
      label: "flex items-center cursor-pointer",
      svgIcon: "block w-[28px] h-[28px] stroke-white stroke-[3]"
    },

  '.question-answered': {
    backgroundColor: 'rgba(25, 179, 148, 0.05)'
  },
  '.question-content .question-root': {
    border: '1px solid lightgray',
    borderRadius: '5px',
    borderLeft: '4px solid #18a689',
    padding: '20px',
    margin: '10px 0'
  },
  '.question-content .question-root-checkboxes': {
    borderLeft: '4px solid orange'
  },
  '.question-title-required': {
    color: '#e60a3e'
  }
}